resources:
  - ../../base
namePrefix: dev-
replicas:
  - name: capstone-app
    count: 1
images:
  - name: talha884/my-capstone-app
    newTag: 6caca35
patches:
  - target:
      kind: Deployment
      name: capstone-app
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/env/1/value
        value: dev
