apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstone-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: capstone-app
  template:
    metadata:
      labels:
        app: capstone-app
    spec:
      containers:
        - name: capstone-app
          image: talha884/my-capstone-app:latest
          ports:
            - containerPort: 5000

          env:
            - name: APP_VERSION
              value: "v1"
            - name: ENVIRONMENT
              value: "base"
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
          limits:
            cpu: "200m"
            memory: "128Mi"
