apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: capstone-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/YOUR_USERNAME/my-capstone-configs.git
    targetRevision: main
    path: overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: capstone-prod
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
