apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: capstone-staging
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/talhanawaz568/my-capstone-configs.git
    targetRevision: main
    path: overlays/staging
  destination:
    server: https://kubernetes.default.svc
    namespace: capstone-staging
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
